### ISSUE TITLE
[Bug]: Server crash on exp event

### ISSUE THREAD

**Issue by SwimUp** [promcteam/proskillapiparties#13]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

The server crashed with the following errors
	at proskillapi-1.1.8-R0.2-20221217.074426-1.jar//com.sucy.skill.api.player.PlayerClass.giveExp(PlayerClass.java:330)
	at proskillapi-1.1.8-R0.2-20221217.074426-1.jar//com.sucy.skill.api.player.PlayerData.giveExp(PlayerData.java:1450)
	at proskillapi-1.1.8-R0.2-20221217.074426-1.jar//com.sucy.skill.api.player.PlayerData.giveExp(PlayerData.java:1438)
	at prorpgitems-1.0.4-R0.2-20221217.072200-1.jar//su.nightexpress.quantumrpg.modules.list.party.compat.level.IPESkillAPI.giveExp(IPESkillAPI.java:31)
	at prorpgitems-1.0.4-R0.2-20221217.072200-1.jar//su.nightexpress.quantumrpg.modules.list.party.compat.level.IPartyLevelManager.getBalancedExp(IPartyLevelManager.java:49)
	at prorpgitems-1.0.4-R0.2-20221217.072200-1.jar//su.nightexpress.quantumrpg.modules.list.party.compat.level.IPESkillAPI.onExpSkillapi(IPESkillAPI.java:23)
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor834.execute(Unknown Source)

Full LOG:
[crash-2023-02-12_18.47.13-server.txt](https://github.com/promcteam/proskillapiparties/files/10716185/crash-2023-02-12_18.47.13-server.txt)

### Environment

```markdown
- Server Software: Paper 1.19.3
- ProSkillAPI Version:1.1.8-R0.2-20221217.074426-1 
- ProSkillAPIParties Version: 1.1.0.2-20221212.101727-1
- ProMCCore Version:1.0.4-R0.2-20221217.064306-1
- Plugins: ProRPGItems 1.0.4-R0.2-20221217.072200-1
```

### latest.log

<details><summary>latest.log</summary>
<p>

```log

```
[crash-2023-02-12_18.47.13-server.txt](https://github.com/promcteam/proskillapiparties/files/10716187/crash-2023-02-12_18.47.13-server.txt)

</p>
</details>

**Comment by Travja** [comment]
This was posted in proskillapiparties, but is actually a bug with ProRPGItems. Regardless, I believe I've resolved this issue in upcoming commits.
